/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109363-g6c814093d8-20221205"
#endif /* AVUTIL_FFVERSION_H */
